# Generated by Django 3.2.13 on 2022-06-11 06:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_h5', models.CharField(max_length=50)),
                ('title_h2', models.CharField(max_length=50)),
                ('title_p', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='BannerSlider')),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='Blog')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Certificate')),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('categorie_icon_code_To_icofont', models.CharField(max_length=50)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'CourseCategory',
                'verbose_name_plural': 'CourseCategories',
            },
        ),
        migrations.CreateModel(
            name='FREQUENTLY_ASKED_QUESTIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(max_length=200)),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'FREQUENTLY_ASKED_QUESTIONS',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='ImageGallery')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OurAlumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='AlumnusImage')),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'OurAlumnus',
                'verbose_name_plural': 'OurAlumnus',
            },
        ),
        migrations.CreateModel(
            name='OurInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='OurInstructorImage')),
                ('about_instructor', ckeditor_uploader.fields.RichTextUploadingField(max_length=500)),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'OurInstructor',
            },
        ),
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='PartnerImage')),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'OurPartner',
                'verbose_name_plural': 'OurPartner',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='TestimonialImage')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=200)),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='TypeOfVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automobileapp.typeofvehicles')),
            ],
            options={
                'verbose_name': 'TypeOfVehicles',
                'verbose_name_plural': 'TypeOfVehicles',
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_embed_link', models.URLField()),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcommingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course_price', models.IntegerField()),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='UpcommingCourseImage')),
                ('course_duration_for_month', models.IntegerField(blank=True, null=True)),
                ('course_duration_for_day', models.IntegerField(blank=True, null=True)),
                ('course_duration_for_hours', models.IntegerField(blank=True, null=True)),
                ('course_type', models.CharField(choices=[('Recored_Video_Course', 'Recored_Video_Course'), ('Online_Live_Course', 'Online_Live_Course'), ('Ofline_Live_Course', 'Ofline_Live_Course')], max_length=150)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
                ('course_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobileapp.coursecategory')),
                ('type_of_vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobileapp.typeofvehicles')),
            ],
            options={
                'verbose_name': 'UpcommingCourse',
                'verbose_name_plural': 'UpcommingCourse',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course_price', models.IntegerField()),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='CourseImage')),
                ('course_duration_for_month', models.IntegerField(blank=True, null=True)),
                ('course_duration_for_day', models.IntegerField(blank=True, null=True)),
                ('course_duration_for_hours', models.IntegerField(blank=True, null=True)),
                ('course_type', models.CharField(choices=[('Recored_Video_Course', 'Recored_Video_Course'), ('Online_Live_Course', 'Online_Live_Course'), ('Ofline_Live_Course', 'Ofline_Live_Course')], max_length=150)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
                ('course_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobileapp.coursecategory')),
                ('type_of_vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobileapp.typeofvehicles')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
