# Generated by Django 3.2.13 on 2022-06-12 06:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0006_directormessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directormessage',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
