# Generated by Django 3.2.13 on 2022-06-12 07:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0008_mission_and_vission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='EventImage')),
                ('mesdescription', ckeditor.fields.RichTextField()),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
