# Generated by Django 4.0 on 2022-06-12 10:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0014_auto_20220612_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacovarage',
            name='mesdescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
