# Generated by Django 4.0 on 2022-06-12 10:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0015_alter_mediacovarage_mesdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacovarage',
            name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='directormessage',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='mesdescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='frequently_asked_questions',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='mission_and_vission',
            name='mission',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='mission_and_vission',
            name='vission',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='ourinstructor',
            name='about_instructor',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='typeofvehicles',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upcommingcourse',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
