# Generated by Django 3.2.13 on 2022-06-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0026_auto_20220630_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourinstructor',
            old_name='instragram_http_link',
            new_name='instagram_http_link',
        ),
    ]
