# Generated by Django 3.2.7 on 2023-06-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=200)),
                ('regis_number', models.CharField(max_length=29)),
                ('course_name', models.CharField(max_length=400)),
                ('father_name', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('course_type', models.CharField(max_length=300)),
                ('start_and_end_date', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Student_data',
                'verbose_name_plural': 'Student_datas',
            },
        ),
    ]
