# Generated by Django 3.2.7 on 2023-06-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data',
            name='student_id',
        ),
    ]
