# Generated by Django 3.2.7 on 2023-06-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0002_remove_student_data_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='student_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
