# Generated by Django 3.2.13 on 2022-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0002_orderpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Roket', 'Roket')], max_length=150),
        ),
    ]
