# Generated by Django 3.2.13 on 2023-01-23 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0041_auto_20230123_1433'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrolled', '0003_alter_orderpayment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='StudentCertificate')),
                ('certificate_id', models.CharField(max_length=150)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automobileapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
