# Generated by Django 3.2.13 on 2023-01-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0007_rename_paymentid_bkashpayment_paymentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bkashpayment',
            old_name='paymentId',
            new_name='paymentID',
        ),
    ]
