# Generated by Django 3.2.13 on 2023-03-20 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrolled', '0009_bkashpaymentexecute'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkashpaymentexecute',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
