# Generated by Django 3.2.13 on 2023-03-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0011_remove_bkashpaymentexecute_updatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('course', models.CharField(max_length=200)),
                ('permanent_a', models.CharField(max_length=200)),
                ('present_a', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'BookInStudent',
                'verbose_name_plural': 'BookInStudents',
            },
        ),
    ]
