# Generated by Django 3.2.13 on 2023-03-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0012_bookinstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstudent',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
