# Generated by Django 3.2.13 on 2023-03-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0014_bokingnow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInStudent',
        ),
    ]
