# Generated by Django 3.2.7 on 2023-04-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0017_auto_20230406_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bkashpayment',
            old_name='title',
            new_name='course_title',
        ),
    ]
