# Generated by Django 3.2.7 on 2023-04-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0018_rename_title_bkashpayment_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bokingnow',
            old_name='permanent_a',
            new_name='permanent_address',
        ),
        migrations.RenameField(
            model_name='bokingnow',
            old_name='present_a',
            new_name='present_address',
        ),
        migrations.AddField(
            model_name='bokingnow',
            name='tentative_admission_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
