# Generated by Django 3.2.7 on 2023-04-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0020_alter_bokingnow_tentative_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bokingnow',
            name='tentative_admission_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
