# Generated by Django 3.2.7 on 2023-04-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0021_alter_bokingnow_tentative_admission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bkashpayment',
            name='course_title',
        ),
    ]
