# Generated by Django 3.2.7 on 2023-04-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0025_order_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bokingnow',
            old_name='course',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='bokingnow',
            old_name='permanent_address',
            new_name='course_titel',
        ),
        migrations.RemoveField(
            model_name='bokingnow',
            name='present_address',
        ),
    ]
