# Generated by Django 3.2.7 on 2023-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0026_auto_20230410_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='bokingnow',
            name='ins_org',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
