# Generated by Django 3.2.7 on 2023-04-16 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0044_auto_20230410_1134'),
        ('enrolled', '0027_bokingnow_ins_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkashpaymentexecute',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automobileapp.course'),
        ),
    ]
