# Generated by Django 3.2.7 on 2023-04-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled', '0028_bkashpaymentexecute_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashpaymentexecute',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
