# Generated by Django 3.2.13 on 2022-06-12 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0012_directormessage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directormessage',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
