# Generated by Django 4.0 on 2022-06-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0016_remove_mediacovarage_image_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediacovarage',
            old_name='mesdescription',
            new_name='description',
        ),
    ]
