# Generated by Django 4.0 on 2022-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0018_alter_blog_slug_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofvehicles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='VehiclesImage'),
        ),
    ]
