# Generated by Django 3.2.13 on 2022-06-26 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0020_alter_typeofvehicles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('time', models.CharField(choices=[('10:00am - 12:00pm', '10:00am - 12:00pm'), ('3:00pm - 5:00pm', '3:00pm - 5:00pm'), ('6:00pm - 8:00pm', '6:00pm - 8:00pm')], max_length=100)),
                ('date', models.DateTimeField()),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobileapp.typeofvehicles')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobileapp.coursecategory')),
            ],
        ),
    ]
