# Generated by Django 3.2.13 on 2022-06-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0025_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourinstructor',
            name='facebook_http_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourinstructor',
            name='instragram_http_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourinstructor',
            name='linkedin_http_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
