# Generated by Django 3.2.13 on 2023-01-24 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='city',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='userip',
            name='country',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='userip',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userip',
            name='regionName',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
