# Generated by Django 3.2.13 on 2023-01-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20230124_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userip',
            old_name='regionName',
            new_name='division',
        ),
    ]
