# Generated by Django 3.2.13 on 2023-01-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_userip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='user_ip',
            field=models.CharField(max_length=150),
        ),
    ]
