# Generated by Django 3.2.13 on 2023-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_userip_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
