# Generated by Django 3.2.13 on 2023-01-24 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_userip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
