# Generated by Django 3.2.13 on 2022-06-11 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
