# Generated by Django 3.2.13 on 2022-06-12 06:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0005_auto_20220611_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='DirectorImage')),
                ('message', ckeditor.fields.RichTextField(max_length=500)),
                ('ordering', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
