# Generated by Django 3.2.13 on 2022-06-12 07:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0007_alter_directormessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission_and_Vission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', ckeditor.fields.RichTextField()),
                ('vission', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
