# Generated by Django 3.2.13 on 2022-06-12 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0011_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='directormessage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
