# Generated by Django 4.0 on 2022-06-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0019_typeofvehicles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofvehicles',
            name='image',
            field=models.ImageField(upload_to='VehiclesImage'),
        ),
    ]
