# Generated by Django 3.2.13 on 2022-06-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0024_remove_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automobileapp.coursetype'),
        ),
    ]
