# Generated by Django 3.2.13 on 2022-07-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0027_rename_instragram_http_link_ourinstructor_instagram_http_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobileapp.coursecategory')),
            ],
        ),
        migrations.AlterField(
            model_name='bannerslider',
            name='title_h2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bannerslider',
            name='title_h5',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='FindedCourse',
        ),
    ]
