# Generated by Django 3.2.13 on 2022-07-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0028_auto_20220701_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ourinstructor',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ourinstructor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upcommingcourse',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
