# Generated by Django 3.2.13 on 2022-07-23 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0030_auto_20220705_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobileapp.blog')),
            ],
        ),
    ]
