# Generated by Django 3.2.13 on 2022-07-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0031_blogscomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogscomment',
            old_name='post',
            new_name='blogs',
        ),
    ]
