# Generated by Django 3.2.13 on 2022-07-23 07:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0032_rename_post_blogscomment_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourinstructor',
            name='about_instructor',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1500),
        ),
    ]
