# Generated by Django 3.2.13 on 2022-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0033_alter_ourinstructor_about_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
