# Generated by Django 3.2.13 on 2022-07-23 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0034_blog_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
