# Generated by Django 3.2.13 on 2022-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0036_alter_blog_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRADUTED_FROM_HERE', models.IntegerField()),
                ('NUMBER_OF_INSTRUCTOR', models.IntegerField()),
                ('YEARS_ON_MARKET', models.IntegerField()),
                ('PRESENT_STUDENTS', models.IntegerField()),
            ],
        ),
    ]
