# Generated by Django 3.2.13 on 2023-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0038_blog_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
