# Generated by Django 3.2.7 on 2023-04-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0041_auto_20230123_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='automobileapp.coursetype'),
        ),
    ]
