# Generated by Django 3.2.7 on 2023-04-10 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobileapp', '0043_alter_course_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forenquiry',
            old_name='f_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='forenquiry',
            name='l_name',
        ),
        migrations.AlterField(
            model_name='forenquiry',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobileapp.course'),
        ),
    ]
